GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiTW8iLCJpYXQiOjE2NzU1MjI3MzIsImV4cCI6MTY3NTUyMjc1Mn0.gLmSeIrXI1d_wD1HlFzS58MifIklltVvu582OFK9cig



###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiTW8iLCJpYXQiOjE2NzU1MjI2NjJ9.SfdNx5TcHIW6sD6-81qwwI7TYsXmczR7250KT_LgSoA"
}


###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiTW8iLCJpYXQiOjE2NzU1MjI2NjJ9.SfdNx5TcHIW6sD6-81qwwI7TYsXmczR7250KT_LgSoA"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Mo"
}